server:
  port: 8083
spring:
  application:
    name: ai-service
  mongodb:
    uri: mongodb://localhost:27017/recommendations
    database: recommendations
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/